---
collections:
  - name: awx.awx
  - name: amazon.aws
  - name: theforeman.foreman
  - name: ovirt.ovirt
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.windows
  - name: redhatinsights.insights
  - name: community.general
